---


- name: system packages | install openssl
  yum:
    name: "{{ item }}"
    state: latest

  with_items:
    - openssl 
    - python-pip

- name: install pip package
  pip:
    name: pyOpenSSL
 
- name: Create directory
 
  file:
 
    path: "{{ item }}"
 
    state: directory
 
    mode: 0755
  with_items:
    - /etc/ssl/private/
    - /etc/ssl/csr
 
- name: Generate an OpenSSL private key

  openssl_privatekey:

    path: /etc/ssl/private/msd.pem

- name: Generate an OpenSSL Certificate Signing Request
 
  openssl_csr:
    path: /etc/ssl/csr/msd.csr

    privatekey_path: /etc/ssl/private/msd.pem
 
    country_name: CZ
 
    organization_name: MSD
 
    email_address: juan@gmail.com

    common_name: www.msd.com

 
- name: Generate a self signed certificate
 
  openssl_certificate:
 
    path: /etc/ssl/certs/nginx-selfsigned.crt
 
    privatekey_path: /etc/ssl/private/msd.pem
 
    csr_path: /etc/ssl/csr/msd.csr
 
    provider: selfsigned 
